/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.raven.form;

import com.raven.Model2.NXB;
import com.raven.Model2.TacGia;
import com.raven.Model2.TheLoai;
import com.raven.Service.NXB_TGgetAll;
import com.raven.form.NXB_Dialog.ActionType;
import com.raven.form.TacGia_Dialog.ActionType1;
import com.raven.form.TheLoai_Dialog.ActionType2;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RAVEN
 */
public final class Form_QLNXB_TG extends javax.swing.JPanel {

    private final DefaultTableModel dtm1;
    private final DefaultTableModel dtm2;
    private final DefaultTableModel dtm3;
    private List<TacGia> listTG = new ArrayList<>();
    private List<TheLoai> listTL = new ArrayList<>();
    private List<NXB> listNXB = new ArrayList<>();
    private final NXB_TGgetAll sv = new NXB_TGgetAll();

    /**
     * Creates new form Form_1
     */
    public Form_QLNXB_TG() {
        initComponents();
        dtm1 = (DefaultTableModel) tbTG.getModel();
        dtm2 = (DefaultTableModel) tbTL.getModel();
        dtm3 = (DefaultTableModel) tbNXB.getModel();
        listTG = sv.getAllTG();
        showData1(listTG);
        listTL = sv.getAllTL();
        showData2(listTL);
        listNXB = sv.getAllNXB();
        showData3(listNXB);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        xoaNXBbtn = new javax.swing.JButton();
        suaNXBbtn = new javax.swing.JButton();
        themNXBbtn = new javax.swing.JButton();
        CbxNXB = new javax.swing.JComboBox<>();
        searchNXB = new javax.swing.JTextField();
        panelBorder1 = new com.raven.swing.PanelBorder();
        jLabel2 = new javax.swing.JLabel();
        spTable = new javax.swing.JScrollPane();
        tbNXB = new com.raven.swing.Table();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        xoaTG = new javax.swing.JButton();
        suaTG = new javax.swing.JButton();
        themMoiTG = new javax.swing.JButton();
        CbxTG = new javax.swing.JComboBox<>();
        searchTG = new javax.swing.JTextField();
        panelBorder2 = new com.raven.swing.PanelBorder();
        jLabel3 = new javax.swing.JLabel();
        spTable1 = new javax.swing.JScrollPane();
        tbTG = new com.raven.swing.Table();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        xoaTL = new javax.swing.JButton();
        suaTL = new javax.swing.JButton();
        themTL = new javax.swing.JButton();
        CbxTL = new javax.swing.JComboBox<>();
        searchTL = new javax.swing.JTextField();
        panelBorder3 = new com.raven.swing.PanelBorder();
        jLabel11 = new javax.swing.JLabel();
        spTable2 = new javax.swing.JScrollPane();
        tbTL = new com.raven.swing.Table();
        jLabel12 = new javax.swing.JLabel();

        xoaNXBbtn.setBackground(new java.awt.Color(18, 64, 118));
        xoaNXBbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        xoaNXBbtn.setForeground(new java.awt.Color(249, 232, 151));
        xoaNXBbtn.setText("Xóa");
        xoaNXBbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaNXBbtnActionPerformed(evt);
            }
        });

        suaNXBbtn.setBackground(new java.awt.Color(18, 64, 118));
        suaNXBbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        suaNXBbtn.setForeground(new java.awt.Color(249, 232, 151));
        suaNXBbtn.setText("Sửa");
        suaNXBbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaNXBbtnActionPerformed(evt);
            }
        });

        themNXBbtn.setBackground(new java.awt.Color(18, 64, 118));
        themNXBbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        themNXBbtn.setForeground(new java.awt.Color(249, 232, 151));
        themNXBbtn.setText("Thêm mới");
        themNXBbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themNXBbtnActionPerformed(evt);
            }
        });

        CbxNXB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "A-Z", "Z-A" }));
        CbxNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxNXBActionPerformed(evt);
            }
        });

        searchNXB.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        searchNXB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchNXBKeyReleased(evt);
            }
        });

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Quản lí nhà xuất bản");

        spTable.setBorder(null);

        tbNXB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Nhà xuất bản", "Mô tả", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbNXB.getTableHeader().setReorderingAllowed(false);
        spTable.setViewportView(tbNXB);

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(spTable, javax.swing.GroupLayout.PREFERRED_SIZE, 1044, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spTable, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/search.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(CbxNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 244, Short.MAX_VALUE)
                .addComponent(themNXBbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(suaNXBbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xoaNXBbtn)
                .addGap(27, 27, 27))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(20, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchNXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CbxNXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(xoaNXBbtn)
                            .addComponent(suaNXBbtn)
                            .addComponent(themNXBbtn))))
                .addContainerGap(621, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(70, Short.MAX_VALUE)
                    .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(16, 16, 16)))
        );

        jTabbedPane1.addTab("Nhà xuất bản", jPanel1);

        xoaTG.setBackground(new java.awt.Color(18, 64, 118));
        xoaTG.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        xoaTG.setForeground(new java.awt.Color(249, 232, 151));
        xoaTG.setText("Xóa");
        xoaTG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaTGActionPerformed(evt);
            }
        });

        suaTG.setBackground(new java.awt.Color(18, 64, 118));
        suaTG.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        suaTG.setForeground(new java.awt.Color(249, 232, 151));
        suaTG.setText("Sửa");
        suaTG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaTGActionPerformed(evt);
            }
        });

        themMoiTG.setBackground(new java.awt.Color(18, 64, 118));
        themMoiTG.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        themMoiTG.setForeground(new java.awt.Color(249, 232, 151));
        themMoiTG.setText("Thêm mới");
        themMoiTG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themMoiTGActionPerformed(evt);
            }
        });

        CbxTG.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "A-Z", "Z-A" }));
        CbxTG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxTGActionPerformed(evt);
            }
        });

        searchTG.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        searchTG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTGKeyReleased(evt);
            }
        });

        panelBorder2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Quản lí tác giả");

        spTable1.setBorder(null);

        tbTG.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên tác giả", "Mô tả", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbTG.getTableHeader().setReorderingAllowed(false);
        spTable1.setViewportView(tbTG);

        javax.swing.GroupLayout panelBorder2Layout = new javax.swing.GroupLayout(panelBorder2);
        panelBorder2.setLayout(panelBorder2Layout);
        panelBorder2Layout.setHorizontalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spTable1, javax.swing.GroupLayout.PREFERRED_SIZE, 1048, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        panelBorder2Layout.setVerticalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spTable1, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/search.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchTG, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(CbxTG, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 244, Short.MAX_VALUE)
                .addComponent(themMoiTG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(suaTG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xoaTG)
                .addGap(27, 27, 27))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addComponent(panelBorder2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(19, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchTG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CbxTG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(xoaTG)
                            .addComponent(suaTG)
                            .addComponent(themMoiTG))))
                .addContainerGap(621, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(66, Short.MAX_VALUE)
                    .addComponent(panelBorder2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(16, 16, 16)))
        );

        jTabbedPane1.addTab("Tác giả", jPanel2);

        xoaTL.setBackground(new java.awt.Color(18, 64, 118));
        xoaTL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        xoaTL.setForeground(new java.awt.Color(249, 232, 151));
        xoaTL.setText("Xóa");
        xoaTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaTLActionPerformed(evt);
            }
        });

        suaTL.setBackground(new java.awt.Color(18, 64, 118));
        suaTL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        suaTL.setForeground(new java.awt.Color(249, 232, 151));
        suaTL.setText("Sửa");
        suaTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaTLActionPerformed(evt);
            }
        });

        themTL.setBackground(new java.awt.Color(18, 64, 118));
        themTL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        themTL.setForeground(new java.awt.Color(249, 232, 151));
        themTL.setText("Thêm mới");
        themTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themTLActionPerformed(evt);
            }
        });

        CbxTL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "A-Z", "Z-A" }));
        CbxTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxTLActionPerformed(evt);
            }
        });

        searchTL.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        searchTL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTLKeyReleased(evt);
            }
        });

        panelBorder3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Quản lí thể loại");

        spTable2.setBorder(null);

        tbTL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên thể loại", "Mô tả", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbTL.getTableHeader().setReorderingAllowed(false);
        spTable2.setViewportView(tbTL);

        javax.swing.GroupLayout panelBorder3Layout = new javax.swing.GroupLayout(panelBorder3);
        panelBorder3.setLayout(panelBorder3Layout);
        panelBorder3Layout.setHorizontalGroup(
            panelBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spTable2, javax.swing.GroupLayout.PREFERRED_SIZE, 1054, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        panelBorder3Layout.setVerticalGroup(
            panelBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spTable2, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/search.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchTL, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(CbxTL, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 244, Short.MAX_VALUE)
                .addComponent(themTL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(suaTL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xoaTL)
                .addGap(27, 27, 27))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addComponent(panelBorder3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(16, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CbxTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(xoaTL)
                            .addComponent(suaTL)
                            .addComponent(themTL))))
                .addContainerGap(621, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(65, Short.MAX_VALUE)
                    .addComponent(panelBorder3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(16, 16, 16)))
        );

        jTabbedPane1.addTab("Thể loại", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void suaNXBbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaNXBbtnActionPerformed
        // TODO add your handling code here:
        int row = tbNXB.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn một hàng để sửa", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        NXB_Dialog nxb = new NXB_Dialog(null, true, ActionType.EDIT);
        nxb.detail(row);
        nxb.setVisible(true);
        listNXB = sv.getAllNXB();
        showData3(listNXB);
    }//GEN-LAST:event_suaNXBbtnActionPerformed

    private void themNXBbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themNXBbtnActionPerformed
        // TODO add your handling code here:
        NXB_Dialog nxb = new NXB_Dialog(null, true, ActionType.ADD);
        nxb.setVisible(true);
        listNXB = sv.getAllNXB();
        showData3(listNXB);
    }//GEN-LAST:event_themNXBbtnActionPerformed

    private void suaTGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaTGActionPerformed
        // TODO add your handling code here:
        int row = tbTG.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn một hàng để sửa", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        TacGia_Dialog nxb = new TacGia_Dialog(null, true, ActionType1.EDIT);
        nxb.detail(row);
        nxb.setVisible(true);
        listTG = sv.getAllTG();
        showData1(listTG);
    }//GEN-LAST:event_suaTGActionPerformed

    private void themMoiTGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themMoiTGActionPerformed
        // TODO add your handling code here:
        TacGia_Dialog tg = new TacGia_Dialog(null, true, ActionType1.ADD);
        tg.setVisible(true);
        listTG = sv.getAllTG();
        showData1(listTG);
    }//GEN-LAST:event_themMoiTGActionPerformed

    private void suaTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaTLActionPerformed
        // TODO add your handling code here:
        int row = tbTL.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn một hàng để sửa", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        TheLoai_Dialog nxb = new TheLoai_Dialog(null, true, ActionType2.EDIT);
        nxb.detail(row);
        nxb.setVisible(true);
        listTL = sv.getAllTL();
        showData2(listTL);
    }//GEN-LAST:event_suaTLActionPerformed

    private void themTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themTLActionPerformed
        // TODO add your handling code here:
        TheLoai_Dialog tg = new TheLoai_Dialog(null, true, ActionType2.ADD);
        tg.setVisible(true);
        listTL = sv.getAllTL();
        showData2(listTL);
    }//GEN-LAST:event_themTLActionPerformed

    private void xoaNXBbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaNXBbtnActionPerformed
        // TODO add your handling code here:
        int row = tbNXB.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn một hàng để xóa", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int choice = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
        if (choice != JOptionPane.YES_OPTION) {
            return; // Nếu người dùng không đồng ý xóa, thoát khỏi phương thức
        }
        NXB_Dialog nxb = new NXB_Dialog(null, true, ActionType.EDIT);
        nxb.detail(row);
        nxb.delete();
        listNXB = sv.getAllNXB();
        showData3(listNXB);
    }//GEN-LAST:event_xoaNXBbtnActionPerformed

    private void xoaTGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaTGActionPerformed
        // TODO add your handling code here:
        int row = tbTG.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn một hàng để xóa", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int choice = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
        if (choice != JOptionPane.YES_OPTION) {
            return; // Nếu người dùng không đồng ý xóa, thoát khỏi phương thức
        }
        TacGia_Dialog nxb = new TacGia_Dialog(null, true, ActionType1.EDIT);
        nxb.detail(row);
        nxb.delete();
        listTG = sv.getAllTG();
        showData1(listTG);
    }//GEN-LAST:event_xoaTGActionPerformed

    private void xoaTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaTLActionPerformed
        // TODO add your handling code here:
        int row = tbTL.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn một hàng để xóa", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int choice = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
        if (choice != JOptionPane.YES_OPTION) {
            return; // Nếu người dùng không đồng ý xóa, thoát khỏi phương thức
        }
        TheLoai_Dialog nxb = new TheLoai_Dialog(null, true, ActionType2.EDIT);
        nxb.detail(row);
        nxb.delete();
        listTL = sv.getAllTL();
        showData2(listTL);
    }//GEN-LAST:event_xoaTLActionPerformed

    private void searchNXBKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchNXBKeyReleased
        // TODO add your handling code here:
        String keyword = searchNXB.getText().trim();

        // Thực hiện tìm kiếm trong danh sách NXB dựa trên từ khóa
        List<NXB> result = listNXB.stream()
                .filter(nxb -> nxb.getTen().toLowerCase().contains(keyword.toLowerCase()))
                .collect(Collectors.toList());

        // Hiển thị kết quả tìm kiếm trên bảng
        showData3(result);
    }//GEN-LAST:event_searchNXBKeyReleased

    private void searchTGKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTGKeyReleased
        // TODO add your handling code here:
        String keyword = searchTG.getText().trim();
        List<TacGia> result = listTG.stream()
                .filter(tg -> tg.getTen().toLowerCase().contains(keyword.toLowerCase()))
                .collect(Collectors.toList());
        showData1(result);
    }//GEN-LAST:event_searchTGKeyReleased

    private void searchTLKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTLKeyReleased
        // TODO add your handling code here:
        String keyword = searchTL.getText().trim();
        List<TheLoai> result = listTL.stream()
                .filter(tl -> tl.getTen().toLowerCase().contains(keyword.toLowerCase()))
                .collect(Collectors.toList());
        showData2(result);
    }//GEN-LAST:event_searchTLKeyReleased

    private void CbxNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxNXBActionPerformed
        // TODO add your handling code here:
        if (CbxNXB.getSelectedItem().equals(" ")) {
            listNXB = sv.getAllNXB();
            showData3(listNXB);
        } else if (CbxNXB.getSelectedItem().equals("A-Z")) {
            AZNXB(listNXB);
        } else if (CbxNXB.getSelectedItem().equals("Z-A")) {
            ZANXB(listNXB);
        }
    }//GEN-LAST:event_CbxNXBActionPerformed

    private void CbxTGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxTGActionPerformed
        // TODO add your handling code here:
        if (CbxTG.getSelectedItem().equals(" ")) {
            listTG = sv.getAllTG();
            showData1(listTG);
        } else if (CbxTG.getSelectedItem().equals("A-Z")) {
            AZTG(listTG);
        } else if (CbxTG.getSelectedItem().equals("Z-A")) {
            ZATG(listTG);
        }
    }//GEN-LAST:event_CbxTGActionPerformed

    private void CbxTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxTLActionPerformed
        // TODO add your handling code here:
        if (CbxTL.getSelectedItem().equals(" ")) {
            listTL = sv.getAllTL();
            showData2(listTL);
        } else if (CbxTL.getSelectedItem().equals("A-Z")) {
            AZTL(listTL);
        } else if (CbxTL.getSelectedItem().equals("Z-A")) {
            ZATL(listTL);
        }
    }//GEN-LAST:event_CbxTLActionPerformed

    public void showData1(List<TacGia> listVC) {
        dtm1.setRowCount(0);
        listVC.forEach(c -> dtm1.addRow(new Object[]{
            c.getId(), c.getTen(), c.getMoTa(), c.getTrangThai()
        }));
    }

    public void showData2(List<TheLoai> listVC) {
        dtm2.setRowCount(0);
        listVC.forEach(c -> dtm2.addRow(new Object[]{
            c.getId(), c.getTen(), c.getMoTa(), c.getTrangThai()
        }));
    }

    public void showData3(List<NXB> listVC) {
        dtm3.setRowCount(0);
        listVC.forEach(c -> dtm3.addRow(new Object[]{
            c.getId(), c.getTen(), c.getMoTa(), c.getTrangThai()
        }));
    }

    public void AZNXB(List<NXB> listVC) {
        // Sắp xếp danh sách theo tên NXB từ A đến Z
        Collections.sort(listVC, (nxb1, nxb2) -> nxb1.getTen().compareToIgnoreCase(nxb2.getTen()));
        dtm3.setRowCount(0);
        listVC.forEach(c -> dtm3.addRow(new Object[]{
            c.getId(), c.getTen(), c.getMoTa(), c.getTrangThai()
        }));
    }

    public void AZTG(List<TacGia> listVC) {
        // Sắp xếp danh sách theo tên Tác giả từ A đến Z
        Collections.sort(listVC, (tg1, tg2) -> tg1.getTen().compareToIgnoreCase(tg2.getTen()));
        dtm1.setRowCount(0);
        listVC.forEach(c -> dtm1.addRow(new Object[]{
            c.getId(), c.getTen(), c.getMoTa(), c.getTrangThai()
        }));
    }

    public void AZTL(List<TheLoai> listVC) {
        // Sắp xếp danh sách theo tên Thể loại từ A đến Z
        Collections.sort(listVC, (tl1, tl2) -> tl1.getTen().compareToIgnoreCase(tl2.getTen()));
        dtm2.setRowCount(0);
        listVC.forEach(c -> dtm2.addRow(new Object[]{
            c.getId(), c.getTen(), c.getMoTa(), c.getTrangThai()
        }));
    }

    public void ZANXB(List<NXB> listVC) {
        // Sắp xếp danh sách theo tên NXB từ Z đến A
        Collections.sort(listVC, (nxb1, nxb2) -> nxb2.getTen().compareToIgnoreCase(nxb1.getTen()));
        dtm3.setRowCount(0);
        listVC.forEach(c -> dtm3.addRow(new Object[]{
            c.getId(), c.getTen(), c.getMoTa(), c.getTrangThai()
        }));
    }

    public void ZATL(List<TheLoai> listVC) {
        // Sắp xếp danh sách theo tên Thể loại từ Z đến A
        Collections.sort(listVC, (tl1, tl2) -> tl2.getTen().compareToIgnoreCase(tl1.getTen()));
        dtm2.setRowCount(0);
        listVC.forEach(c -> dtm2.addRow(new Object[]{
            c.getId(), c.getTen(), c.getMoTa(), c.getTrangThai()
        }));
    }

    public void ZATG(List<TacGia> listVC) {
        // Sắp xếp danh sách theo tên Tác giả từ Z đến A
        Collections.sort(listVC, (tg1, tg2) -> tg2.getTen().compareToIgnoreCase(tg1.getTen()));
        dtm1.setRowCount(0);
        listVC.forEach(c -> dtm1.addRow(new Object[]{
            c.getId(), c.getTen(), c.getMoTa(), c.getTrangThai()
        }));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbxNXB;
    private javax.swing.JComboBox<String> CbxTG;
    private javax.swing.JComboBox<String> CbxTL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private com.raven.swing.PanelBorder panelBorder1;
    private com.raven.swing.PanelBorder panelBorder2;
    private com.raven.swing.PanelBorder panelBorder3;
    private javax.swing.JTextField searchNXB;
    private javax.swing.JTextField searchTG;
    private javax.swing.JTextField searchTL;
    private javax.swing.JScrollPane spTable;
    private javax.swing.JScrollPane spTable1;
    private javax.swing.JScrollPane spTable2;
    private javax.swing.JButton suaNXBbtn;
    private javax.swing.JButton suaTG;
    private javax.swing.JButton suaTL;
    private com.raven.swing.Table tbNXB;
    private com.raven.swing.Table tbTG;
    private com.raven.swing.Table tbTL;
    private javax.swing.JButton themMoiTG;
    private javax.swing.JButton themNXBbtn;
    private javax.swing.JButton themTL;
    private javax.swing.JButton xoaNXBbtn;
    private javax.swing.JButton xoaTG;
    private javax.swing.JButton xoaTL;
    // End of variables declaration//GEN-END:variables
}
